import React from "react";

function MyProjects() {
  return (
    <section>
      <div>
        <image></image>
        <div>
          <h3></h3>
          <p></p>
          <p></p>
        </div>
        <div>
          <button></button>
          <button></button>
        </div>
      </div>
      <div>
        <image></image>
        <div>
          <h3></h3>
          <p></p>
          <p></p>
        </div>
        <div>
          <button></button>
          <button></button>
        </div>
      </div>
      <div>
        <image></image>
        <div>
          <h3></h3>
          <p></p>
          <p></p>
        </div>
        <div>
          <button></button>
          <button></button>
        </div>
      </div>
      <div>
        <image></image>
        <div>
          <h3></h3>
          <p></p>
          <p></p>
        </div>
        <div>
          <button></button>
          <button></button>
        </div>
      </div>
      <div>
        <image></image>
        <div>
          <h3></h3>
          <p></p>
          <p></p>
        </div>
        <div>
          <button></button>
          <button></button>
        </div>
      </div>
    </section>
  );
}
export { MyProjects };
